apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: "#{APP_NAME}#"
  name: "#{APP_NAME}#"
  namespace: "#{NAMESPACE}#"
spec:
  # type: NodePort
  type: LoadBalancer  
  ports:
    - port: 3000
      name: http
      protocol: TCP
      targetPort: 3000
  selector:
    app: "#{APP_NAME}#"